# Generated by Django 3.2.7 on 2021-09-05 08:50

import django.contrib.postgres.indexes
from django.db import migrations

# Gin indexing을 사용하기 위해 설정한다.
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='NewGinIndex'),
        ),
    ]
